//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPEXTVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_VENTAS_CLIENTES
    {
        public string Clave_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Mail { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Producto { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
        public int ID { get; set; }
    }
}
